class NicknamesList {

    constructor() {
        this.nicknames = [
            'xXx_DragonSlayer_xXx',
            'NoobSlayer3000',
            'SneakyPete',
            'JiggleMaster',
            'LilPwny',
            'GameOnDude',
            'Slay3r',
            'GamerGirl88',
            'xXx_BlackWidow_xXx',
            'ProGamer9000',
            'SneakySnake',
            'JiggleMaster2000',
            'Maverick',
            'AceOfSpades',
            'ShadowHunter',
            'MasterChief',
            'PixelWarrior',
            'NinjaAssassin',
            'CaptainObvious',
            'ThunderBolt',
            'SilentKnight',
            'IronFist',
            'DarkAngel',
            'DragonSlayer',
            'FireMage',
            'SonicBoom',
            'RapidFire',
            'QuickDraw',
            'SilentButDeadly',
            'Bullseye',
            'TheShadow',
            'FastFingers',
            'QuickSilver',
            'Ricochet',
            'BionicCommando',
            'TheFlash',
            'Starlight',
            'Moonwalker',
            'SkyHigh',
            'StormChaser',
            'NightShade',
            'TheViper',
            'LaserBeam',
            'ThunderStrike',
            'RicoSuave',
            'SonicScream',
            'FastLane',
            'PhantomPain',
            'Shredder',
        ]
    }
}

module.exports = NicknamesList